name: python库
on:
  push:
    branches:
      - main
jobs:
  run_batch_script:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run .bat script
        run: 1_Main/2/安装.bat
